version: '3.1'

services:
  db:
    image: postgres
    restart: always
    volumes: 
        - ./data/db:/var/lib/postgresql    
    ports:
      - 5432:5432 
    environment:
      - POSTGRES_DB=orm_data
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=muky0000
  
  
  adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080